language: scala

script:
  - sbt ++$TRAVIS_SCALA_VERSION test 'set scalaJSStage in Global := FullOptStage' test

scala:
  - 2.12.6
  - 2.12.4
  - 2.12.3

jdk:
  - openjdk8

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install jsdom